"""Vendor the webfonts used by Kusanagi-AI as local woff2 + a local @font-face sheet.

Run from the repo root:  python scripts/fetch_fonts.py

Writes static/vendor/fonts/. Nothing at page-load time then reaches Google, which
keeps the Content-Security-Policy tight and stops leaking visitors to a third party.

Inter and JetBrains Mono are both *variable* fonts: Google serves one identical file
per unicode subset and varies only the @font-face descriptors. We dedupe on content
hash and emit a single face per (family, subset) with a font-weight range, which is
what the variable-font spec wants anyway.
"""
import hashlib
import io
import os
import re
import shutil
import urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Inter:wght@300;400;600;800"
           "&family=JetBrains+Mono:wght@400;700"
           "&display=swap")
# A modern UA is what makes Google serve woff2 rather than ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

KEEP_SUBSETS = ("latin", "latin-ext")
OUT = os.path.join("static", "vendor", "fonts")


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def parse(css):
    """Yield (family, weight, style, subset, unicode_range, url) for kept subsets."""
    for block in re.split(r"(?=/\*\s*[a-z-]+\s*\*/)", css):
        label = re.match(r"/\*\s*([a-z-]+)\s*\*/", block.strip())
        if not label or "@font-face" not in block:
            continue
        subset = label.group(1)
        if subset not in KEEP_SUBSETS:
            continue
        # unicode-range is load-bearing: latin and latin-ext are different files
        # with otherwise identical descriptors, so without it the browser picks
        # one face and the other subset never loads.
        yield (
            re.search(r"font-family:\s*'([^']+)'", block).group(1),
            int(re.search(r"font-weight:\s*(\d+)", block).group(1)),
            re.search(r"font-style:\s*(\w+)", block).group(1),
            subset,
            re.search(r"unicode-range:\s*([^;}]+)", block).group(1).strip(),
            re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1),
        )


def main():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    faces = list(parse(fetch(CSS_URL)))
    if not faces:
        raise SystemExit("no @font-face blocks parsed -- did the Google CSS format change?")

    # Download once per distinct URL, then group by the bytes we actually got.
    blobs, groups = {}, {}
    for family, weight, style, subset, urange, url in faces:
        if url not in blobs:
            blobs[url] = fetch(url, binary=True)
        digest = hashlib.md5(blobs[url]).hexdigest()
        key = (family, style, subset, urange, digest)
        groups.setdefault(key, []).append(weight)

    sheet, total = [], 0
    for (family, style, subset, urange, digest), weights in sorted(groups.items()):
        name = "%s-%s.woff2" % (family.replace(" ", ""), subset)
        path = os.path.join(OUT, name)
        if not os.path.exists(path):
            url = next(u for u in blobs if hashlib.md5(blobs[u]).hexdigest() == digest)
            with open(path, "wb") as f:
                f.write(blobs[url])
            size = os.path.getsize(path)
            total += size
            print("  ok %7d  %s" % (size, path))

        lo, hi = min(weights), max(weights)
        span = str(lo) if lo == hi else "%d %d" % (lo, hi)
        sheet.append(
            "@font-face {\n"
            "  font-family: '%s';\n"
            "  font-style: %s;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            "  src: url('./%s') format('woff2');\n"
            "  unicode-range: %s;\n"
            "}\n" % (family, style, span, name, urange)
        )

    header = ("/* %s, vendored from Google Fonts (%s subsets).\n"
              "   Self-hosted so no page load reaches a third party.\n"
              "   Generated by scripts/fetch_fonts.py -- do not hand-edit. */\n\n"
              % (" + ".join(sorted({f for f, _, _, _, _, _ in faces})),
                 ", ".join(KEEP_SUBSETS)))
    out = os.path.join(OUT, "fonts.css")
    io.open(out, "w", encoding="utf-8", newline="\n").write(header + "\n".join(sheet))
    print("  ok %7d  %s  (%d faces, %d KB of woff2)"
          % (os.path.getsize(out), out, len(sheet), total // 1024))


if __name__ == "__main__":
    main()
